### ISSUE TITLE
Game image requirement

### ISSUE THREAD

**Issue by hyperscope** [winnitron/winnitron_reborn#87]
Are games meant to be uploaded in linear steps? (Details>Images>Zip Upload>Executable)
You are allowed to proceed past the "Images" step despite the requirement.

As well [Requirements for Winnitron Games](https://github.com/winnitron/WinnitronLauncher/wiki/Requirements-for-Winnitron-Games) calls for "...making sure the game has an executable and at least one screenshot." but the screenshot seems to be overwritten by the one included in the upload process.

**Comment by aaronklaassen** [comment]
Yeah you can skip past because the game won't show up to anyone other than you until you click 'publish' at the end (which checks for the existence of at least one image and a zip/executable). So it doesn't matter what order you do things in.

There are some fixes/improvements planned to the image management (#73, #84, #85, #86) which will address this, I think - what do you mean the screenshot is overwritten?

**Comment by hyperscope** [comment]
If I upload a picture of a dog on the website but include a cat in the zip it will still show the dog on the launcher.

**Comment by aaronklaassen** [comment]
Yep this is intended behaviour - allowing the game dev to explicitly choose which image is the one they want to show up in the menu. Especially since it's not unlikely that a game zip could contain a whole bunch of png's and we need to know which one to show.

I'm not sure what that logic looks like in the Launcher right now but it may well need to be tweaked.

**Comment by hyperscope** [comment]
So with the current logic it will never show the image included in the zip because you are forced to upload a image during the game upload process. I suppose the only way you'd get the image from the zip is if you did a manual install of a game?

**Comment by hyperscope** [comment]
Again if I follow instructions listed on the requirements page 

> "uploading it to the Winnitron Network..."

 which requires a image to be uploaded during the "Images" step 

> "and making sure the game has an executable and at least one screenshot."

 it will never show the image in the zip correct?

**Comment by aaronklaassen** [comment]
It should use the one from the website, yes. Downloading it and saving it locally is part of the sync.
