### ISSUE TITLE
Game download restrictions

### ISSUE THREAD

**Issue by hyperscope** [winnitron/winnitron_reborn#95]
**Issues**: Registering a non existent Winnitron with the sole purpose to download the games
**Resolution**: Builder Approval
**Comment**: Is there a priority to ensure only legitimate Winnitron owners can download games from the network? Whats to stop users from simply registering a non existent Winnitron with the sole purpose to download the games?

**Comment by aaronklaassen** [comment]
Only users flagged as 'builders' can register a Winnitron and download the games. The process is very rudimentary right now, you're right: it's just a button that sends me an email with their request. But I'd like to expand that so that it requires a photo of their machine (even if it's still a work in process) or something.

**Comment by hyperscope** [comment]
Ah I suppose I just don't remember getting approved, as it would have been awhile ago.
